# Generated by Django 4.2.4 on 2023-09-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_about_alter_product_about_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'BotUser', 'verbose_name_plural': 'BotUsers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Enter username', max_length=150, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='name',
            field=models.CharField(blank=True, help_text='Enter name', max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.IntegerField(db_index=True, help_text='Enter Telegram ID', unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select Category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.subcategory', verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SubCategory'),
        ),
        migrations.AlterModelTable(
            name='botuser',
            table='BotUser',
        ),
    ]
